apiVersion: apps/v1
kind: Deployment
metadata:
  name: landscape-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landscape-service
  template:
    metadata:
      labels:
        app: landscape-service
    spec:
      containers:
        - name: landscape-service
          image: dev-landscape-service
          ports:
            - containerPort: 8081
          env:
            - name: SERVICE_PORT
              value: "8081"
            - name: RANCHER_GRPC_HOST
              value: rancher-service
            - name: RANCHER_GRPC_PORT
              value: "9093"
            - name: HANDYMAN_GRPC_HOST
              value: handyman-service
            - name: HANDYMAN_GRPC_PORT
              value: "9092"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_NAME_DB
              value: database
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: landscape-service
spec:
  selector:
    app: landscape-service
  ports:
    - port: 8081
      targetPort: 8081
  type: NodePort