apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher-service
  template:
    metadata:
      labels:
        app: rancher-service
    spec:
      containers:
        - name: rancher-service
          image: dev-rancher-service
          ports:
            - containerPort: 8083
            - containerPort: 9093
          env:
            - name: SERVICE_PORT
              value: "8083"
            - name: GRPC_PORT
              value: "9093"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_NAME_DB
              value: database
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-service
spec:
  selector:
    app: rancher-service
  ports:
    - name: app
      port: 8083
      targetPort: 8083
    - name: grpc
      port: 9093
      targetPort: 9093
  type: NodePort
