server:
  port: ${LANDSCAPE_PORT}

grpc:
  client:
    rancher:
      address: localhost:9093
      negotiation-type: plaintext
    handyman:
      address: localhost:9091
      negotiation-type: plaintext

spring:
  application:
    name: landscape

management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
