server:
  port: ${RANCHER_PORT}

grpc:
  server:
    port: ${GRPC_PORT}

spring:
  application:
    name: rancher

management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
